portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from techguy.views import index, register


urlpatterns = [
    path('admin/', admin.site.urls),
    path("techguy/", include("techguy.urls")),
    path("", index, name="index"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', register, name="register")
]

techguy/urls.py
from django.urls import path
# from .views import TechguyListView,TechguyDetailView, mail
from techguy import views

urlpatterns =[
    # path("", TechguyListView.as_view(), name="index"),
    # path("<slug:slug>/", TechguyDetailView.as_view(), name="TechguyDetailView"),
    path("show", views.show, name='show'),
    path("mail/", views.ContactForm.as_view(), name="mail"),
    path('create', views.create),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),  
    path('cookie', views.showcookie, name="cookie"),
    path('visitcookie', views.visitcookie, name="visitcookie"),
    path('deletecookie', views.deletecookie, name="deletecookie"),

    # Sessions
    path('createsession/', views.create_session),
    path('accesssession', views.access_session),

    # Order Crud Operations

    # Customer Operations
    path('customers/', views.customers, name="customers"),
    path('customers/create', views.create_customer, name="create_customer"),
    path('customers/detail/<str:pk>', views.customer_detail, name="detail_customer"),
    path('customers/update/<int:id>', views.update_customer, name="update_customer"),
    path('customers/delete/<int:id>', views.delete_customer, name="delete_customer"),

    # Product Operations
    path('products/', views.products, name="products"),
    path('products/create', views.create_product, name="create_product"),
    path('products/detail/<str:pk>', views.product_detail, name="detail_product"),
    path('products/update/<int:id>', views.update_product, name="update_product"),
    path('products/delete/<int:id>', views.delete_product, name="delete_product"),

    # Order Operations
    # path('orders/', views.orders, name="orders"),
    path("orders/", views.ListOrder.as_view(), name="orders"),
    path('orders/create', views.CreateOrder.as_view(), name="create_order"),
    path('orders/detail/<str:pk>', views.DetailOrder.as_view(), name="detail_order"),
    path('orders/update/<str:pk>', views.UpdateOrder.as_view(), name="update_order"),
    path('orders/delete/<int:pk>', views.DeleteOrder.as_view(), name="delete_order"),
]

techguy/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.http import JsonResponse

# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Techguy(models.Model):
    title = models.CharField(max_length=100, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(default='',max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    email = models.CharField(max_length=40, null=True)
    category = models.ManyToManyField('Category', related_name='posts', blank=True)
    # status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            'pk': self.id,
            'slug': self.slug
        }
        return reverse('article-pk-slug-detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Techguy, self).save(*args, **kwargs)

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=10, null=True)
    email = models.CharField(max_length=30, null=True)
    phone = models.CharField(max_length=10 ,null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

class Product(models.Model):
    PRODUCT_TYPE = (
        ("Physical", "Physical"),
        ("Downloadable", "Downloadable")
    )
    name = models.CharField(max_length=20)
    sku = models.CharField(max_length=10)
    quantity = models.IntegerField()
    product_type = models.CharField(choices=PRODUCT_TYPE, default="Physical", max_length=50)

    def __str__(self):
        return self.name

class Order(models.Model):
    ORDER_STATUS = (
        ("Pending", "Pending"),
        ("Dispatched", "Dispatched"),
        ("Delivered", "Delivered")
    )
    order_id = models.CharField(max_length=50)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.CharField(choices=ORDER_STATUS, max_length=50)

    class Meta:
        verbose_name =  ("Order")
        verbose_name_plural = ("Orders")

    def __str__(self):
        return self.order_id

    # def get_absolute_url(self):
    #     return reverse("Order_detail", kwargs={"pk": self.pk})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Django </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
</head>
<body>
    <style>
        body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #2b2b2b !important;
    }
    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }
    .masthead {
        background: #3398E1;
        height: auto;
        padding-bottom: 15px;
        padding-top: 10px;
    }
    footer{
        bottom: 0;
        width: -webkit-fill-available;
        position: fixed;
    }
</style>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Webshot</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="/">Home</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'orders' %}">Orders</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'customers' %}">Customers</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'products' %}">Products</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item text-black">
                        <a href="{% url 'logout'%}" class="nav-link text-black font-weight-bold">logout</a>
                    </li>
                    {% else %}
                        <li><a href="{% url 'login'%}?next={{request.path}}"  class="nav-link text-black font-weight-bold" >Login</a></li>   
                    {% endif %} 
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    
    {% endblock content %}
    <!-- Footer -->
    <footer class="bg-grey">
        <p class="m-0 text-center btn-danger">Copyright &copy; Django Webshot</p>
    </footer>
</body>
</html>

templates/contact.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        color:#fff;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>

{%endblock%}

templates/create.html
{% extends 'base.html' %} {% block content %}

<form method="POST" class="post-form" action="/techguy/create">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">title :</label>  
    <div class="col-sm-4">  
      {{ form.title }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">description :</label>  
    <div class="col-sm-4">  
      {{ form.description }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">technology :</label>  
    <div class="col-sm-4">  
      {{ form.technology }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">email :</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock content %}

templates/detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{{ blog.title }}</h1>
        <p class=" text-muted">{{ blog.technology }} | {{ blog.created_on }}</p>
        <p class="card-text ">{{ blog.description | safe }}</p>
        <a href="{% url 'mail' %}"><button>Email this person</button></a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/edit.html
{% extends 'base.html' %} {% block content %}
{{ formset.errors }}
{{ formset.non_field_errors }}
{{ form.errors }}
{{ form.non_field_errors }}
<form method="POST" class="post-form" action="/techguy/update/{{ techguy.id }}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">title :</label>  
    <div class="col-sm-4">  
        <input type="text" name="title" id="id_title" required maxlength="200" value="{{ techguy.title }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">description :</label>  
    <div class="col-sm-4">  
        <input type="text" name="description" id="id_description" required maxlength="100" value="{{ techguy.description }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">technology :</label>  
    <div class="col-sm-4">  
        <input type="text" name="technology" id="id_technology" required maxlength="254" value="{{ techguy.technology }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">email :</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="100" value="{{ techguy.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
{% endblock content %}

templates/index.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->

        <div class="col-md-8 mt-3 left">
            <a href="techguy/create"><span class="glyphicon glyphicon-pencil" >Add</span></a> 
            <div class="card mb-4">
                <div class="card-body">
                </div>
            </div>
        </div>
        <div class="col-md-8 mt-3 left">
            <a href="techguy/create"><span class="glyphicon glyphicon-pencil" >Add</span></a> 
            {% for post in techguy %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.technology }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.description|slice:":200" }}</p>
                    {% comment %} <a href="{% url 'TechguyDetailView' post.slug  %}" class="btn btn-primary">Read More &rarr;</a> {% endcomment %}
                    {{ category }}

                   {% for cat in category %} <p>
                        {{ cat }}
                    </p>
                    {% endfor %}
                </div>
            </div>
            <a href="techguy/edit/{{ post.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="techguy/delete/{{ post.id }}">Delete</a>  
            {% endfor %}
        </div>
        
    </div>
</div>
{%endblock%}